stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  #dependsOn: Plan
  condition: and(not(failed()), not(canceled()))
  jobs:

  # Build Linux
  - template: ../Jobs/build.yml
    parameters:
      #imageType: ${{ parameters ['ImageType-Linux'] }} # Index syntax must be used when variable contains a '-'
      imageType: $(ImageType_Linux)
      location: '${{ variables.ImageLocation }}'
  
  # Build Windows
  - template: ../Jobs/build.yml
    parameters:
      #imageType: ${{ parameters ['ImageType-Windows'] }} # Index syntax must be used when variable contains a '-'
      imageType: '${{ variables.ImageType_Windows }}'
      location: '${{ variables.ImageLocation }}'