stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  #dependsOn: Plan
  condition: and(not(failed()), not(canceled()))
  jobs:

  # Build Linux
  - template: ../Jobs/build.yml
    parameters:
      imageType: ${{ variables.ImageType-Linux }}
      location: ${{ variables.ImageLocation }}
  
  # Build Windows
  - template: ../Jobs/build.yml
    parameters:
      imageType: ${{ variables.ImageType-Windows}}
      location: ${{ variables.ImageLocation }}