stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  #dependsOn: Plan
  condition: and(not(failed()), not(canceled()))
  jobs:

  # Build Linux
  - template: ../Jobs/build_linux.yml
  
  # Build Windows
  - template: ../Jobs/build_windows.yml
